<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    public function run(): void
    {

        $events = [
            [
                'nama_event' => 'Festival Pandhalungan Jember 2024',
                'kategori' => 'Festival',
                'deskripsi' => 'Festival budaya terbesar dan paling komprehensif di Jawa Timur ',
                'tanggal_mulai' => Carbon::now()->addDays(7)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(9)->format('Y-m-d'),
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '23:00:00',
                'lokasi' => 'Alun-Alun Jember',
                'tipe_lokasi' => 'offline',
                'kapasitas_peserta' => 15000,
                'harga_ticket' => 0,
                'nama_penyelenggara' => 'Dinas Kebudayaan Jember',
                'email_penyelenggara' => 'info@budayajember.go.id',
                'no_telepon' => '03311234567 ',
                'icon' => '🎭',
                'rating' => 4.9,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Workshop Intensif Bahasa Jemberan',
                'kategori' => 'Workshop',
                'deskripsi' => 'Pelatihan metodologis intensif selama 3 hari yang dirancang khusus untuk guru SD-SMP ',
                'tanggal_mulai' => Carbon::now()->addDays(20)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(20)->format('Y-m-d'),
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '16:00:00',
                'lokasi' => 'Gedung Kesenian Pendalungan',
                'tipe_lokasi' => 'offline',
                'kapasitas_peserta' => 150,
                'harga_ticket' => 50000,
                'nama_penyelenggara' => 'Sanggar Tari Nusantara',
                'email_penyelenggara' => 'sanggar@tarinusantara.com',
                'no_telepon' => '082345678901',
                'icon' => '💃',
                'rating' => 4.8,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Workshop Batik Motif Tradisional',
                'kategori' => 'Workshop',
                'deskripsi' => 'Pelajari teknik membatik dengan motif khas Pendalungan dari para ahli',
                'tanggal_mulai' => Carbon::now()->addDays(5)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(5)->format('Y-m-d'),
                'waktu_mulai' => '10:00:00',
                'waktu_selesai' => '16:00:00',
                'lokasi' => 'Sanggar Seni Nusantara',
                'tipe_lokasi' => 'offline',
                'kapasitas_peserta' => 50,
                'harga_ticket' => 150000,
                'nama_penyelenggara' => 'Komunitas Batik Jember',
                'email_penyelenggara' => 'batik@jember.com',
                'no_telepon' => '083456789012',
                'icon' => '🎨',
                'rating' => 4.7,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Webinar: Pelestarian Bahasa Daerah di Era Digital',
                'kategori' => 'Webinar',
                'deskripsi' => 'Diskusi tentang strategi melestarikan bahasa daerah menggunakan teknologi',
                'tanggal_mulai' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'waktu_mulai' => '13:00:00',
                'waktu_selesai' => '16:00:00',
                'lokasi' => 'Online (Zoom)',
                'tipe_lokasi' => 'online',
                'kapasitas_peserta' => 500,
                'harga_ticket' => 0,
                'nama_penyelenggara' => 'Pusat Bahasa Nusantara',
                'email_penyelenggara' => 'webinar@bahasanusantara.org',
                'no_telepon' => '084567890123',
                'icon' => '💻',
                'rating' => 4.6,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Workshop Kuliner Tradisional',
                'kategori' => 'Workshop',
                'deskripsi' => 'Belajar memasak makanan khas Pendalungan dari chef berpengalaman',
                'tanggal_mulai' => Carbon::now()->addDays(12)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(12)->format('Y-m-d'),
                'waktu_mulai' => '09:00:00',
                'waktu_selesai' => '15:00:00',
                'lokasi' => 'Pusat Kuliner Tradisional',
                'tipe_lokasi' => 'offline',
                'kapasitas_peserta' => 30,
                'harga_ticket' => 200000,
                'nama_penyelenggara' => 'Chef Association Jember',
                'email_penyelenggara' => 'chef@jember.com',
                'no_telepon' => '085678901234',
                'icon' => '👨‍🍳',
                'rating' => 4.5,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Webinar: Sejarah Kerajaan Pendalungan',
                'kategori' => 'Webinar',
                'deskripsi' => 'Menggali sejarah dan perkembangan kebudayaan Pendalungan',
                'tanggal_mulai' => Carbon::now()->addDays(2)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(2)->format('Y-m-d'),
                'waktu_mulai' => '14:00:00',
                'waktu_selesai' => '17:00:00',
                'lokasi' => 'Online (Google Meet)',
                'tipe_lokasi' => 'online',
                'kapasitas_peserta' => 400,
                'harga_ticket' => 0,
                'nama_penyelenggara' => 'Historian Nusantara',
                'email_penyelenggara' => 'sejarah@nusantara.id',
                'no_telepon' => '086789012345',
                'icon' => '📚',
                'rating' => 4.4,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Pertunjukan Musik Tradisional',
                'kategori' => 'Pertunjukan',
                'deskripsi' => 'Konser musik tradisional dengan instrumen khas daerah',
                'tanggal_mulai' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'waktu_mulai' => '19:00:00',
                'waktu_selesai' => '22:00:00',
                'lokasi' => 'Pendopo Kabupaten',
                'tipe_lokasi' => 'offline',
                'kapasitas_peserta' => 300,
                'harga_ticket' => 25000,
                'nama_penyelenggara' => 'Orchestra Nusantara',
                'email_penyelenggara' => 'musik@nusantara.com',
                'no_telepon' => '087890123456',
                'icon' => '🎵',
                'rating' => 4.7,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Festival Wayang Kulit',
                'kategori' => 'Festival',
                'deskripsi' => 'Pagelaran wayang kulit dengan cerita klasik dari budaya Jawa',
                'tanggal_mulai' => Carbon::now()->addDays(25)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(25)->format('Y-m-d'),
                'waktu_mulai' => '20:00:00',
                'waktu_selesai' => '02:00:00',
                'lokasi' => 'Alun-alun Kota',
                'tipe_lokasi' => 'offline',
                'kapasitas_peserta' => 1000,
                'harga_ticket' => 0,
                'nama_penyelenggara' => 'Dalang Nusantara',
                'email_penyelenggara' => 'wayang@jember.id',
                'no_telepon' => '088901234567',
                'icon' => '🎭',
                'rating' => 4.9,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_event' => 'Kompetisi Fotografi Budaya',
                'kategori' => 'Kompetisi',
                'deskripsi' => 'Lomba fotografi dengan tema kekayaan budaya Pendalungan',
                'tanggal_mulai' => Carbon::now()->addDays(18)->format('Y-m-d'),
                'tanggal_selesai' => Carbon::now()->addDays(18)->format('Y-m-d'),
                'waktu_mulai' => '08:00:00',
                'waktu_selesai' => '17:00:00',
                'lokasi' => 'Museum Pendalungan',
                'tipe_lokasi' => 'offline',
                'kapasitas_peserta' => 100,
                'harga_ticket' => 75000,
                'nama_penyelenggara' => 'Photography Club Jember',
                'email_penyelenggara' => 'photo@jember.com',
                'no_telepon' => '089012345678',
                'icon' => '📷',
                'rating' => 4.6,
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('events')->insert($events);
    }
}